DROP TRIGGER IF EXISTS PARTICULIER;
DELIMITER //
CREATE TRIGGER PARTICULIER
BEFORE INSERT ON PARTICULIER
FOR EACH ROW
BEGIN
  INSERT INTO CLIENT(ADRESSEC,TELC,MAILC,MDPC) VALUES (new.ADRESSEC,new.TELC,new.MAILC,new.MDPC);
  SET NEW.NUMEROC = (SELECT MAX(NUMEROC) FROM CLIENT);
END //
DELIMITER ;


DROP TRIGGER IF EXISTS ENTREPRISE;
DELIMITER //
CREATE TRIGGER ENTREPRISE
BEFORE INSERT ON ENTREPRISE
FOR EACH ROW
BEGIN
  INSERT INTO CLIENT(ADRESSEC,TELC,MAILC,MDPC) VALUES (new.ADRESSEC,new.TELC,new.MAILC,new.MDPC);
  SET NEW.NUMEROC = (SELECT MAX(NUMEROC) FROM CLIENT);
END //
DELIMITER ;